export enum Permiso {
  CONSULTA_ARRENDADORES = 1,
  ACTUALIZAR_ARRENDADORES = 2,
  AGREGAR_ARRENDADOR = 3,
  ELIMINAR_ARRENDADOR = 4,

  CONSULTAR_USUARIO = 5,
  AGREGAR_USUARIO = 6,
  ACTUALIZAR_USUARIO = 7,
  ELIMINAR_USUARIO = 8,

  AGREGAR_MODULO = 9,
  ACTUALIZAR_MODULO = 10,
  CONSULTAR_MODULO = 11,
  ELIMINAR_MODULO = 12,

  AGREGAR_PERMISO = 13,
  ACTUALIZAR_PERMISO = 14,
  CONSULTAR_PERMISOS = 15,
  ELIMINAR_PERMISO = 16,

  AGREGAR_INPC = 17,
  ACTUALIZAR_INPC = 18,
  CONSULTAR_INPC = 19,
  ELIMINAR_INPC = 20,

  AGREGAR_FACTORES = 21,
  ACTUALIZAR_FACTOR = 22,
  CONSULTAR_FACTORES = 23,
  ELIMINAR_FACTOR = 24,

  AGREGAR_FORMULA = 25,
  ACTUALIZAR_FORMULA = 26,
  CONSULTAR_FORMULAS = 27,
  ELIMINAR_FORMULA = 28,

  CONSULTAR_BITACORA = 29,

  AGREGAR_ROL = 30,
  ACTUALIZAR_ROL = 31,
  CONSULTAR_ROLES = 32,
  ELIMINAR_ROL = 33,

  CONSULTAR_ARRENDADORES_MAPA = 34,

  AGREGAR_SERVICIO = 35,
  ACTUALIZAR_SERVICIO = 36,
  CONSULTAR_SERVICIOS = 37,
  ELIMINAR_SERVICIO = 38,

  CONSULTAR_METODOS_DE_PAGO = 39,

  CONSULTAR_TABLERO = 40,

  CONSULTAR_INMUEBLES = 41,
  ACTUALIZAR_INMUEBLE = 42,
  AGREGAR_INMUEBLE = 43,
  ELIMINAR_INMUEBLE = 44,

  CONSULTAR_SERVICIOS_INMUEBLES = 45,
  ACTUALIZAR_ARRENDATARIOS = 46,
  AGREGAR_ARRENDATARIOS = 47,
  ELIMINAR_ARRENDATARIOS = 48,
  CONSULTAR_ARRENDATARIOS = 49,
  CONSULTAR_SERVICIOS_ARRENDATARIOS = 50,

  PERMISO_RESERVADO_RENT_ROL = 51,

  ELIMINAR_INSTALACION = 52,
}
